AWSTemplateFormatVersion: '2010-09-09'
Description: VPC and subnets for demo-api-docker-ecs-dev

Resources:

  VPC: #Nube 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default

  Subnet1: #Divisiones de la vpc donde se van a desplegar fisicamente los contenedores
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC #Asosiacion de servicio a la vpc creada
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Sub '10.0.0.0/20'
      MapPublicIpOnLaunch: true

  Subnet2: #Divisiones de la vpc donde se van a desplegar fisicamente los contenedores
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC #Asosiacion de servicio a la vpc creada
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Sub '10.0.32.0/20'
      MapPublicIpOnLaunch: true

  InternetGateway: #Crea un gateway para permitir la conectividad a Internet desde la VPC esta ruta permite que el tráfico salga de la VPC hacia Internet.
    Type: 'AWS::EC2::InternetGateway'

  VPCGatewayAttachment: #Asocia un gateway para permitir la conectividad a Internet desde la VPC.
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      InternetGatewayId: !Ref InternetGateway #Asosiacion de servicio a el internetGateAway
      VpcId: !Ref VPC #Asosiacion de servicio a la vpc creada 

  RouteTable: #Crea una tabla de rutas para gestionar el trafico de la vpc hacia el exterior
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC #Asosiacion de servicio a la vpc creada

  RouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet1 #Asosiacion de servicio a la subnet
      RouteTableId: !Ref RouteTable #Asosiacion de servicio a el routetable anterior

  RouteTableAssociation2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref Subnet2 #Asosiacion de servicio a la subnet
      RouteTableId: !Ref RouteTable #Asosiacion de servicio a el routetable anterior

  InternetRoute: # Establece la ruta hacia internet desde la vpc
    Type: 'AWS::EC2::Route'
    DependsOn: VPCGatewayAttachment
    Properties:
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: '0.0.0.0/0'

Outputs:

  VPC:
    Description: VPC
    Value: !Ref VPC
    Export:
      Name: 'VPC'

  Subnet1:
    Description: 'Subnet 1 on AZ1'
    Value: !Ref Subnet1
    Export:
      Name: 'Subnet1'

  Subnet2:
    Description: 'Subnet 2 on AZ2'
    Value: !Ref Subnet2
    Export:
      Name: 'Subnet2'
